name: Build Resume

on:
  push:
    branches: [main]
    paths:
      - "*.md"
      - ".github/workflows/build-resume.yml"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:3.8
        with:
          args: >
            README.md
            --standalone
            --output=Calvin-Nel-Resume.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: Calvin-Nel-Resume.pdf
